### PR TITLE
Allowing returning body parts in the response

### PR DESCRIPTION
**Pull request by danielcuervo**
Hello! I write in english since this is public and maybe not everyone using the library knows catalan nor spanish.

I think Miguel already talked to you about me opening a Pull request, here are details:

I added a function in the vars filler in order to be able to return parts of the body in the return, in order to do that I used a json parse library called gabs, I also had to add array support by array index since gabs allows to do operations in arrays but not in the way I wanted.

In order to use the feature I have used the same place holder you are using for the body {{request.body}} but after "body" you can define any path you want to navigate through the body parts of the request.

So, imagine the body request is as follows:
```json
{
    "car" :  { 
        "doors": [
            {"name": "front door", "color": "red"}, 
            {"name": "front door", "color": "blue"}
        ]
    }
}
```

If in the response config you write: The color of the door is: {{request.body.car.doors.1.color}}
it would return: The color of the door is "blue"

If in the response config you write: {"colors": {{request.body.car.doors.color}}}
it would return: {"colors": ["red", "blue"]}  (this is default gabs array access)

If in the response config you write: {"doors": {{request.body.car.doors}}}
it would return: {"doors": [{"name": "front door", "color": "red"}, {"name": "front door", "color":"blue"}]}

If in the response config you write: {"nonexistent": {{request.body.whatever}}}
it would return: {"nonexistent": {{request.body.whatever}}}

I think it's quite straight forward, feel free to comment/edit/close this PR, I have not developed much in go so be kind, hehe. Any advise would be more than welcomed! :D

### CODE REVIEW

**Comment by danielcuervo** [comment]
Just saw you did an update lol

**Comment by danielcuervo** [comment]
In the new functionality you included you almost all features I was covering on this pull request. The only one missing is the ability to navigate through arrays (I might be missing how to do it), it might be worth to take a look to support it?

**Comment by jmartincmp** [comment]
You won't trust me, but one colleague found the same lack of functionality and implemented it just 2 days ago. Anyway the ability to navigate through arrays it's really nice. It would be great if you can added it. 

Many thanks for your efforts.

**Comment by danielcuervo** [comment]
Quan m'ha donat conflicte ho ve vist, quina casualitat, jajajaja
Probaré a veure si trobo temps per extendre el que ha fet el teu company per poder accedir als arrays.

**Pull request closed without merging**
