### PR TITLE
multiple requests in single yaml file

### LINKED ISSUE #80: Multiple requests in single yaml file
YAML format can hold several documents in a single file; It would be convenient if the config file could hold multiple requests through
```
--- # First request
request: ...
response: ...
--- # Second request
request: ...
response: ...
```
It's more convenient to keep requests for a single test together in a single file.

### PR DESCRIPTION
**Pull request by ndk**
close #80 
Maybe it doesn't seem the perfect solution, but I didn't want to make too many changes. :)

### CODE REVIEW

**Comment by jmartin82** [comment]
Thanks for your contribution, it going to be really useful.

The code looks good to me, I have no comments about it, but I was wondering if you can add an example file in the config folder in this PR, I'm pretty sure you used one example in order to test this feature. If not, no worries I can create one.

Cheers,

**Comment by ndk** [comment]
Could I use unit-test toolkits such as Testify, or Goconvey? Using only the standard package for writing unit-tests is a little bit inconvenient to me. :)

**Comment by jmartin82** [comment]
If you don't mind I would like to keep it without and specific unit-test toolkit, I think this keeps really low the specific knowledge you need to contribute to the project.

I hope you understand.

**Comment by jmartin82** [comment]
Thanks for your contribution! I will create a new version with your changes ASAP!

**Comment by jmartin82** [comment]
Due to this issue (https://github.com/jmartin82/mmock/issues/103)  I've temporarily reverted this feature, sorry.

**Pull request merged**
